### ISSUE TITLE
Problem when using serverless.yml config

### ISSUE THREAD

**Issue by hukus** [SamWSoftware/serverless-auto-swagger#13]
Hi! Great tool but I am having a configuration problem. I am using the serverless config file in .yml version and trying to config this gives me this error:

`Serverless: Configuration warning at 'functions.lookup.events[0].http': unrecognized property 'responses'`

My config:
```
frameworkVersion: '>=2.0.0 <3.0.0'

plugins:
  - serverless-auto-swagger
  - serverless-dotenv-plugin
  - serverless-cf-vars
  - serverless-esbuild
  - serverless-iam-roles-per-function
  - serverless-offline

  lookup:
    handler: src/handler/lookup.handler
    memorySize: 512
    timeout: 25
    events:
      - http:
          method: GET
          path: /transports
          responses: {
            200: { 
              description: 'List of possible transport options',
              bodyType: 'LookupTransportResponse',
            },
          }
          cors:
            origin: '*'
            headers: '*'
```

Might be because of using `esbuild`?

**Comment by hukus** [comment]
Also when looking at console while building, the only mention of swagger I see is:

```
offline: Function names exposed for local invocation by aws-sdk:
           * lookup: api-test-lookup
           * .........other endpoints
           * swaggerJSON: undefined
```

**Comment by hukus** [comment]
...and of course I solved it immediately after creating and issue. 
By adding curly braces here:

```
custom:
  autoswagger: {
    generateSwaggerOnDeploy: true
  }
```

**Comment by hukus** [comment]
But now it just says I have no operations defined, when in fact I am using this on repository full of nedpoints with various operations. I even tested removing the `responses` definition from endpoints and the `autoswagger` from custom. It loads the types but sees no operations. Are we sure this works with the .yml version of the file? Could it be caused by esbuild?
![image](https://user-images.githubusercontent.com/16256404/149929129-02c12c1d-6c17-4029-b246-10befbbc744a.png)

**Comment by ezzy1337** [comment]
@hukus I've been using this plugin with a serverless.yml file. The only difference I can see is I didn't mix JSON with YAML. For instance my response section looks like this.
```
functions:
  health:
    handler: handler.health
    events:
      - http:
          method: get
          path: /health
          cors: true
          responses:
            '200':
              description: A Successful responses
            '400':
              description: You done gone broke it now
```

Also if you are only using the generateSwaggerOnDeploy in the custom configuration like this.
```
custom:
    autoswagger:
        generateSwaggerOnDeploy: true
```
you can omit all of that. The default setting for generateSwaggerOnDeploy is true so in this case you wouldn't have to provide anything for the custom config.

**Comment by hukus** [comment]
Thanks.

So I found final reason for problems:
**The capitalised** `GET`
```
    events:
      - http:
          method: GET
```
The plugin keeps the string capitalised and the swagger parsers can't parse that correctly. When I changed the methods to `get` and `post` the plugin works as it should.

Also please keep in mind: list this plugin first - if it is not before other plugins it doesn't build stuff correctly.

**Comment by ferrjohnpainagan** [comment]
> Hi! Great tool but I am having a configuration problem. I am using the serverless config file in .yml version and trying to config this gives me this error:
> 
> `Serverless: Configuration warning at 'functions.lookup.events[0].http': unrecognized property 'responses'`
> 
> My config:
> 
> ```
> frameworkVersion: '>=2.0.0 <3.0.0'
> 
> plugins:
>   - serverless-auto-swagger
>   - serverless-dotenv-plugin
>   - serverless-cf-vars
>   - serverless-esbuild
>   - serverless-iam-roles-per-function
>   - serverless-offline
> 
>   lookup:
>     handler: src/handler/lookup.handler
>     memorySize: 512
>     timeout: 25
>     events:
>       - http:
>           method: GET
>           path: /transports
>           responses: {
>             200: { 
>               description: 'List of possible transport options',
>               bodyType: 'LookupTransportResponse',
>             },
>           }
>           cors:
>             origin: '*'
>             headers: '*'
> ```
> 
> Might be because of using `esbuild`?

Hi I'm also using serverless.yaml for the config and I'm wondering how you were able to import the bodyType value 'LookupTransportResponse'. Thanks!

**Comment by bfaulk96** [comment]
> Hi I'm also using serverless.yaml for the config and I'm wondering how you were able to import the bodyType value 'LookupTransportResponse'. Thanks!

@ferrjohnpainagan 

This is mentioned in the [adding data types section](https://github.com/completecoding/serverless-auto-swagger#adding-data-types). By default, the tool looks in `src/types/api-types.d.ts` for your exported typescript objects, but you can specify a different file in your configuration if necessary.
