### ISSUE TITLE
Document: Add Swagger tags

### ISSUE THREAD

**Issue by bfaulk96** [SamWSoftware/serverless-auto-swagger#19]
![Screen Shot 2022-01-31 at 1 13 05 PM](https://user-images.githubusercontent.com/12897328/151849537-23a926b1-fbf3-46c9-8c71-20c1f27e5af7.png)

As seen in the screenshot, there is a one collapsible title `default` for all generated API calls. This should ideally be split per lambda if possible, with the lambda name (or customizable?).
This behavior can also be seen in the how-to YouTube video.

**Update**
You can change these titles by adding `swaggerTags: ['status']` to your `http` event, but this appears to be undocumented. Would be helpful to document it for others to easily use in the future.

**Comment by bfaulk96** [comment]
Expected behavior would be something like

```markdown
# status
GET /v1/status

# enrollments
GET /v1/enrollments
POST /v1/enrollments
```

**Comment by desaintvincent** [comment]
you can use swaggerTags, an array of string

**Comment by bfaulk96** [comment]
> you can use swaggerTags, an array of string

But if there's no way to do this via serverless, it partially defeats the point of this plugin if you have to keep a full swagger.json that keeps up with all endpoints anyway IMO..

**Comment by bfaulk96** [comment]
Scratch that, I just tested and it checks out. Could this be added to the documentation?
