### ISSUE TITLE
Feature Request: Use serverless params

### ISSUE THREAD

**Issue by bfaulk96** [SamWSoftware/serverless-auto-swagger#21]
Currently, `serverless-auto-swagger` requires You to add the following info to your HTTP serverless object:

```typescript
queryStringParameters: {
  foo: {
    required: true,
    type: 'string',
  },
  baz: {
    required: false,
    type: 'string',
  }
}
```
but Serverless already supports clarifying optional/required params via the serverless config as below:

```typescript
request: {
  parameters: {
    querystrings: {
      foo: true,
      baz: false
    },
    paths: {
      bar: true,
    },
  },
}
```

Would it be possible to piggy-back off of the serverless params so that the values can truly be "auto" and not need repeated? Or could both options potentially be used?

- Pro: Define params in one spot, get both Swagger benefits and lambda param enforcement
- Con: Can't define description for each query string when using the serverless setup. Also can't specify number vs string, but I think that's probably not much of an issue since http doesn't send numbers via query strings anyway – everything starts as a string

**Comment by SamWSoftware** [comment]
We've just had APR that delivers this feature. Hopefully get a new version published today

**Comment by moosthuizen42** [comment]
I'm unable to find the PR mentioned. This functionality also is not available in serverless-auto-swagger@2.3.0. Is this still in progress?

**Comment by bfaulk96** [comment]
> I'm unable to find the PR mentioned. This functionality also is not available in serverless-auto-swagger@2.3.0. Is this still in progress?

No, this functionality does not yet exist, and there is currently no PR for it. I've been focusing on features that enable further Swagger functionality for the library, so I haven't had time to look into it

**Comment by bfaulk96** [comment]
https://github.com/SamWSoftware/serverless-auto-swagger/pull/71 Should address this feature, but I still need to get it reviewed and add some docs to the README about it before calling it good.

**Comment by bfaulk96** [comment]
This feature has been added to `v2.5.0` via #71! 🎉
