### ISSUE TITLE
Error after v2.4.0 release

### ISSUE THREAD

**Issue by ronie-san** [SamWSoftware/serverless-auto-swagger#59]
After the v2.4.0 release, I keep getting the following error:

 Type Error ----------------------------------------------

  TypeError: Cannot destructure property 'log' of 'undefined' as it is undefined.
      at new ServerlessAutoSwagger (.\node_modules\serverless-auto-swagger\dist\ServerlessAutoSwagger.js:21:40)
      at PluginManager.addPlugin (.\node_modules\serverless\lib\classes\PluginManager.js:114:28)
      at .\node_modules\serverless\lib\classes\PluginManager.js:163:33
      at Array.forEach (<anonymous>)
      at PluginManager.loadAllPlugins (.\node_modules\serverless\lib\classes\PluginManager.js:163:8)
      at Serverless.init (.\node_modules\serverless\lib\Serverless.js:213:30)
      at async .\node_modules\serverless\scripts\serverless.js:585:7

Also, the path parameters should be documented in the README.md file and the descriptions of these parameters should appear in the generated swagger file.

**Comment by bfaulk96** [comment]
> Also, the path parameters should be documented in the README.md file and the descriptions of these parameters should appear in the generated swagger file.

On this note, I'm not really following. Path parameters are generated directly from the path provided by the user, so there is not really a good way to add a description.

**Comment by bfaulk96** [comment]
> On this note, I'm not really following. Path parameters are generated directly from the path provided by the user, so there is not really a good way to add a description.
As for documentation, there are several ways the README can be improved... But Sam and I are both quite busy. PRs are welcome :)

Update: Sorry, I hadn't looked at this chunk of code before since Sam originally wrote it.
It does appear that as you mentioned in the other issue,
```yaml
parameters:
  someParam: true
```
was previously supported as well.
I've updated this to again allow
```yaml
parameters:
  someParam: true
# and additionally
parameters:
  someParam: 
    required: true
    description: some description here
```
