### ISSUE TITLE
Can we support Creating Swagger Document for Private APIS defined in CFN Template

### ISSUE THREAD

**Issue by sunilnalumachu** [SamWSoftware/serverless-auto-swagger#64]
*To help us debug your issue fill in the basic information below using the options provided*

*Serverless Java Container version*:  2.52.1

*Implementations:*  Node serverless framework

*Framework version:*  serverless version  2.52.1, node: 14.17

*Service:* Private REST API

*Deployment method:* Serverless Framework

## Scenario
*Describe what you are trying to accomplish*

I am trying to use serverless-auto-swagger plugin to generate swagger docs for my private rest apis defined in cloudformation template. I am using node with serverless project with typescript and aws resources.

## Expected behavior
*Describe how you would expect the application to behave*
I am expecting to generate swagger docs for my private rest api defined in cloudformation template which has method and function declaration. So is there any way we can generate swagger docs for private apis defined in cfn template. please let me know. If you can support this feature it would be great

Sample declaration of private apis in cfn template:

GetTestMethod:
      Type: "AWS::ApiGateway::Method"
      Properties:
        HttpMethod: "POST"
        AuthorizationType: "CUSTOM"
        AuthorizerId:
          Ref: "PrivateApiAuthorizer"
        Integration:
          Type: "AWS_PROXY"
          IntegrationHttpMethod: "POST"
          PassthroughBehavior: WHEN_NO_MATCH
          Uri:
            Fn::Sub: "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${GetTestPrivateLambdaFunction.Arn}/invocations"
        ResourceId:
          Ref: "GetTestResource"
        RestApiId:
          Ref: "PrivateApi"

## Actual behavior
*Describe what you are seeing instead*
I don't see any swagger docs created for my private rest apis defined in cfn template.

**Comment by SamWSoftware** [comment]
This plugin is designed to work with apis defined in the serverless framework.
It doesn't read or understand raw cloudformation so won't be able to build the swagger docs from your definition.

There may be other tools out there that do cloudformation to swagger, but that is out of the scope for this plugin
