### ISSUE TITLE
Plugin assumes node_modules directory is in same directory as serverless.yml

### ISSUE THREAD

**Issue by dave-jumptech** [SamWSoftware/serverless-auto-swagger#65]
Hi, this plugin looks really interesting, but when I tried to apply it to my existing project, which has multiple stacks in the repo I got this error:

```
Serverless: Creating Swagger file...
 
 Error ---------------------------------------------------
 
  Error: ENOENT: no such file or directory, lstat './node_modules/serverless-auto-swagger/dist/resources'
 
     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.
``` 

My repo has the following structure:
```
my-repo/
  node_modules/
    ...
  stacks/
    stack-one/
      serverless.yml
      src/
        ...
      test/
        ...
    stack-two/
      serverless.yml
      src/
        ...
      test/
        ...
```

Looking at the code it appears that the relative path `./node_modules` is hard-coded and used to copy resources from the package. Indeed, manually copying `serverless-auto-swagger` to the required path of `my-repo/stacks/stack-one/node_modules/serverless-auto-swagger` allows it to run.

Do you have any plans to support this type of repo structure?

**Comment by bfaulk96** [comment]
PRs are always welcome :)
