### ISSUE TITLE
Is any way to define a array of elements as request / response body?

### ISSUE THREAD

**Issue by Daranix** [SamWSoftware/serverless-auto-swagger#69]
I tried to define a array of elements as bodyType of a response like this:

```
export type ListOfUsers = Array<IUser>;

export interface IUser {
    id: string;
    eid: string;
    displayName: string;
    avatar: string;
    status: number;
    currentTeam: string;
    currentEvent: string;
    currentInstance: number;
}
```

Then i added to the on the http block of the handler definition:

```
        responses: {
          200: {
            bodyType: 'ListOfUsers',
          }
        }
```

But the definition is not getting that type correctly:

![image](https://user-images.githubusercontent.com/13921690/167275229-d1b4d0c8-da02-43bd-bace-a2db17152daf.png)

I expected this:

```
[
  {
  "id": "string",
  "eid": "string",
  "displayName": "string",
  "avatar": "string",
  "status": 0,
  "currentTeam": "string",
  "currentEvent": "string",
  "currentInstance": 0
  }
]
```

Thanks.

**Comment by alanschapira** [comment]
Try using `responseData` instead of `responses`

**Comment by bfaulk96** [comment]
Yeah, `responses` clashes with either serverless itself or other plugins. Honestly it should be removed entirely from the docs and API instead of just warned against. I'd think that would solve your problem

**Comment by SamWSoftware** [comment]
I think I'll also need to redo the video as there are a few things that
have been updated

**Comment by Daranix** [comment]
Yeah! that was the problem, thank you all, also probably when i tried to use responseData i forgot to put the `export` keyword in before the type definition.
